# Generated by Django 6.0.2 on 2026-02-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="content",
        ),
        migrations.AddField(
            model_name="post",
            name="artist",
            field=models.CharField(default="Text", max_length=200),
            preserve_default=False,
        ),
    ]
