# Generated by Django 6.0.2 on 2026-03-19 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('aka', models.CharField(blank=True, max_length=200, verbose_name='Aka')),
                ('article', models.CharField(blank=True, choices=[('The', 'The'), ('A', 'A')], max_length=10, verbose_name='Article')),
                ('banner', models.ImageField(blank=True, default='fallback.jpg', upload_to='')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('aka', ''), models.Q(models.Q(('aka__icontains', ' '), _negated=True), models.Q(('aka__icontains', '_'), _negated=True)), _connector='OR'), name='playlist_artist_aka_rule', violation_error_message='Aka may be blank a string that excludes underscores and spaces')],
            },
        ),
        migrations.CreateModel(
            name='NewTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_artist', to='playlist.artist')),
                ('collaborators', models.ManyToManyField(related_name='track_collaborator', to='playlist.artist')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_on', models.DateField()),
                ('played_at', models.TimeField()),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.newtrack')),
            ],
            options={
                'ordering': ['-played_on', '-played_at', 'track__title'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('played_on', models.DateField()),
                ('played_at', models.TimeField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.artist')),
            ],
        ),
        migrations.AddConstraint(
            model_name='newtrack',
            constraint=models.UniqueConstraint(fields=('title', 'artist'), name='unique_track'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(fields=('played_on', 'played_at'), name='unique_entry'),
        ),
    ]
