# Generated by Django 6.0.2 on 2026-02-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='created_by',
            field=models.DateTimeField(),
        ),
    ]
