# Generated by Django 6.0.2 on 2026-02-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_alter_track_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='played_at',
            field=models.TimeField(blank=True, default='10:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='played_on',
            field=models.DateField(blank=True, default='2026-02-01'),
            preserve_default=False,
        ),
    ]
