# Generated by Django 6.0.2 on 2026-02-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_track_played_at_track_played_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='played_at',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='played_on',
            field=models.DateField(),
        ),
    ]
