# Generated by Django 6.0.2 on 2026-02-26 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_alter_track_played_at_alter_track_played_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='created_by',
        ),
    ]
