# Generated by Django 6.0.2 on 2026-02-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0007_alter_track_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='banner',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
