# Generated by Django 6.0.2 on 2026-02-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0008_artist_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='banner',
        ),
    ]
