# Generated by Django 6.0.2 on 2026-02-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0011_sortablebook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='artist',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='name'),
        ),
    ]
