# Generated by Django 6.0.2 on 2026-02-28 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0012_alter_artist_options_artist_my_order_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SortableBook',
        ),
    ]
